SELECT BOARD_NO, BOARD_TITLE, BOARD_CONTENT, CREATE_DT, READ_COUNT
		FROM BOARD
		WHERE BOARD_TITLE = '안녕';
		
	
	
SELECT BOARD_NO, BOARD_TITLE, BOARD_CONTENT, CREATE_DT, READ_COUNT
FROM BOARD
LEFT JOIN MEMBER USING(MEMBER_NO)
WHERE MEMBER_NM LIKE '왕';


SELECT BOARD_NO, BOARD_TITLE, BOARD_CONTENT, CREATE_DT, READ_COUNT
FROM BOARD
WHERE BOARD_NO = 1;

<!-- 시퀀스는 no cash 만들어야 함.-->

SELECT BOARD_NO , MEMBER_NO  
FROM BOARD 
WHERE BOARD_NO = 5;

UPDATE BOARD SET DELETE_FL = 'N'
WHERE BOARD_NO = 1;

SELECT BOARD_NO , MEMBER_NO ,DELETE_FL
FROM BOARD ;

COMMIT;


INSERT INTO "COMMENT"
VALUES(SEQ_COMMENT_NO.NEXTVAL, '안녕', DEFAULT, DEFAULT, 1, 6);

SELECT *
FROM "COMMENT" 
WHERE BOARD_NO =6;


SELECT COMMENT_CONTENT , MEMBER_NM
FROM "COMMENT"
LEFT JOIN "MEMBER" USING(MEMBER_NO)
WHERE BOARD_NO = 1 AND DELETE_FL ='N';


SELECT MEMBER_NO 
FROM "COMMENT" 
WHERE BOARD_NO = 1 AND COMMENT_NO = 1;



SELECT MEMBER_NO 
		FROM "COMMENT" 
		WHERE BOARD_NO = 1 AND COMMENT_NO = 1 AND MEMBER_NO =1;


UPDATE "COMMENT" SET COMMENT_CONTENT = '뭐야' , CREATE_DT =SYSDATE
WHERE COMMENT_NO =14;
	
SELECT *
FROM "COMMENT";

ROLLBACK;

UPDATE "COMMENT" SET DELETE_FL = 'Y'
WHERE COMMENT_NO =14;	
	
	
	
	
	