SELECT MEMBER_NO, MEMBER_ID, MEMBER_NM, MEMBER_GENDER,
TO_CHAR(ENROLL_DT, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') ENROLL_DT
FROM "MEMBER" 
WHERE MEMBER_ID = 'user01'
AND MEMBER_PW = 'pass01'
AND UNREGISTER_FL = 'N';



SELECT MEMBER_ID
FROM "MEMBER" 
WHERE MEMBER_ID = ?


INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user04', 'pass04', 
	 '유저사', 'M', SYSDATE, DEFAULT);

INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, ?, ?, 
	 ?, ?, SYSDATE, DEFAULT);

	
SELECT MEMBER_ID, MEMBER_NM, MEMBER_GENDER, ENROLL_DT
FROM "MEMBER" 
WHERE MEMBER_ID = 'user01';


UPDATE "MEMBER" SET 
MEMBER_NM  = '유은서', MEMBER_GENDER ='M'
WHERE MEMBER_ID = 'user04'
;

SELECT * FROM "MEMBER";